version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py test &&  # Run Django tests
             gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application"

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: >
      sh -c "yarn install &&
             yarn test --watchAll=false &&  # Run React tests
             yarn start"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: myprojectdb
      POSTGRES_USER: myprojectuser
      POSTGRES_PASSWORD: myprojectpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: